Tutorial
cyclus/cyclus.github.com pull request #293
Opened 2019-06-28 20:33 UTC by gtw2

Updating the Cyclus user tutorial - Compilation of changes from multiple people at ARFC. Also includes random fixes to the website.

2019-06-28 20:45 UTC, katyhuff commented
Unfortunately, this monster PR touches a ton of stuff, including fixes to the install instructions and a start on the tutorial. I'm giong to request reviews from lots of folks....

2019-06-29 13:02 UTC, katyhuff commented on source/user/tutorial/add_arche.rst
> +A sink facility that accepts materials and products with a fixed throughput (per time step) capacity and a lifetime capacity defined by a total inventory size. The inventory size and throughput capac
```suggestion
A sink facility that accepts materials and products with a fixed throughput (per time step) capacity and a lifetime 
capacity defined by a total inventory size. The inventory size and throughput capacity both default to infinite. If a 
recipe is provided, it will request material with that recipe. Requests are made for any number of specified 
commodities.
```

2019-06-29 13:02 UTC, katyhuff commented on source/user/tutorial/add_arche.rst
> +::
```suggestion
.. code-block:: xml
```

2019-06-29 13:02 UTC, katyhuff commented on source/user/tutorial/add_arche.rst
> +The Sink archetype is of the form:
```suggestion
The Sink archetype section is of the form:
```

2019-06-29 13:02 UTC, katyhuff commented on source/user/tutorial/add_arche.rst
> +::
```suggestion
.. code-block:: xml
```

2019-06-29 13:03 UTC, katyhuff commented on source/user/tutorial/add_arche.rst
> +::
```suggestion
.. code-block:: xml
```

2019-06-29 13:03 UTC, katyhuff commented on source/user/tutorial/add_arche.rst
> +::
```suggestion
.. code-block:: xml
```

2019-06-29 13:03 UTC, katyhuff commented on source/user/tutorial/add_arche.rst
> +::
```suggestion
.. code-block:: xml
```

2019-06-29 13:04 UTC, katyhuff commented on source/user/tutorial/add_deploy.rst
> +prototype. And finally at time step 3 the ``1000We Lightwater-1`` will be deployed.
```suggestion
prototype. And finally, at time step 3, the ``1000We Lightwater-1`` will be deployed.
```

2019-06-29 13:05 UTC, katyhuff commented on source/user/tutorial/add_fab.rst
> +The cycamore FuelFab archetype uses the equivalence type method to mix streams of
```suggestion
The cycamore FuelFab archetype uses the _equivalence method_ to mix streams of
```

2019-06-29 13:05 UTC, katyhuff commented on source/user/tutorial/add_fab.rst
> +        <fill_commods> <val>_______</val> </fill_commods>
```suggestion
        <fill_commods> 
            <val>_______</val> 
        </fill_commods>
```

2019-06-29 13:07 UTC, katyhuff commented on source/user/tutorial/add_fab.rst
> +        <fiss_commods><val>_______</val></fiss_commods>
```suggestion
        <fiss_commods>
            <val>_______</val>
        </fiss_commods>
```

2019-06-29 13:08 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +Suppliers then respond to the series of requests with a bid . A bid
```suggestion
Suppliers then respond to the series of requests with a bid. A bid
```

2019-06-29 13:08 UTC, katyhuff commented on source/user/tutorial/add_fab.rst
>  * Filler stream commodity: U-ore
```suggestion
* Filler stream commodity: ``u-ore``
```

2019-06-29 13:09 UTC, katyhuff commented on source/user/tutorial/add_fab.rst
>  * Filler stream recipe: Nat-U
```suggestion
* Filler stream recipe: ``nat-u``
```

2019-06-29 13:09 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +Whenever |CYCLUS| needs
```suggestion
When |CYCLUS| needs
```

2019-06-29 13:10 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +include the recipe for natural uranium, spent fuel, fresh fuel, or any
```suggestion
describe any isotopic vector (e.g. natural uranium, spent fuel, fresh fuel, or any
```

2019-06-29 13:10 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +other material where the isotopic composition needs to be tracked.
```suggestion
other material whose isotopic composition needs to be tracked.)
```

2019-06-29 13:11 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +The commodities section is located right under the ``archetype`` section
```suggestion
The commodities section is located below the ``archetype`` section
```

2019-06-29 13:14 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +
```suggestion
```

2019-06-29 13:14 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +
```suggestion
```

2019-06-29 13:15 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +
```suggestion
```

2019-06-29 13:15 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +Once complete append the commodities section under the archetypes section.
```suggestion
Once complete, append the commodities section under the archetypes section.
```

2019-06-29 13:16 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +also acceptable. For example, U-235 can be expressed as:
```suggestion
also acceptable. For example, :math:`^{235}`\ U can be expressed as:
```

2019-06-29 13:16 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +99.284% uranium-238. The recipe section of a CYCLUS input file is
```suggestion
99.284% :math:`^{238}`\ U. The recipe section of a CYCLUS input file is
```

2019-06-29 13:17 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +example, u-ore has an isotropic composition of 0.711% uranium-235 and
```suggestion
example, u-ore has an isotropic composition of 0.711% :math:`^{235}`\ U and
```

2019-06-29 13:17 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +fuel. We'll be using simple recipes: fresh fuel is 4.0% U-235 by mass,
```suggestion
fuel. We'll be using simple recipes: fresh fuel is 4.0% :math:`^{235}`\ U by mass,
```

2019-06-29 13:18 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +remainder U-238. Spent fuel is 1.1% U-235, 94.0% U-238, 0.9% Pu-239, and
```suggestion
remainder U-238. Spent fuel is 1.1% :math:`^{235}`\ U, 94.0% :math:`^{238}`\ U, 0.9% :math:`^{239}`\ Pu, and
```

2019-06-29 13:18 UTC, katyhuff commented on source/user/tutorial/add_proto.rst
> +4.0% Cs-137.
```suggestion
4.0% :math:`^{137}`\ Cs.
```

2019-06-29 13:24 UTC, katyhuff commented on source/user/tutorial/cyclus_tutorial_recap.rst
> +::
```suggestion
.. code-block:: XML
```

2019-06-29 13:25 UTC, katyhuff commented on source/user/tutorial/data_explorer.rst
> +*CYCLUS* creates a .sqlite file as its output. SQLite is a database file
```suggestion
*CYCLUS* creates an SQLite (``.sqlite``) database file as its output. SQLite is a database file
```

2019-06-29 13:27 UTC, katyhuff commented on source/user/tutorial/data_explorer.rst
> +contents viewed, but these database browsers often aren't helpful.
```suggestion
but these database browsers aren't intended for powerful analysis.
```

2019-06-29 13:27 UTC, katyhuff commented on source/user/tutorial/data_explorer.rst
> +Importing the data into an external function and manipulating it would
```suggestion
Importing the data into an external function and analyzing it
```

2019-06-29 13:27 UTC, katyhuff commented on source/user/tutorial/data_explorer.rst
> +provide more useful information. However, it can still be helpful to
```suggestion
is a more powerful approach. However, it can still be helpful to
```

2019-06-29 13:29 UTC, katyhuff commented on source/user/tutorial/data_explorer.rst
> +An sqlite database can be opened and its
```suggestion
An sqlite database can be opened by viewers like ``sqlitebrowser`` or ``sqliteman``,
```

2019-06-29 13:33 UTC, katyhuff commented on source/user/tutorial/install_launch_cyclus.rst
> +For this tutorial, we only require the Cyclus, Cycamore, and Cymetric". You can
```suggestion
For this tutorial, we only require the Cyclus, Cycamore, and Cymetric. You can
```

2019-06-29 13:33 UTC, katyhuff commented on source/user/tutorial/launch_cyclus.rst
> +Using Cyclus with the Cloud
```suggestion
Using Cyclus in the Cloud
```

2019-06-29 13:35 UTC, katyhuff commented on source/user/tutorial/run_cyclus_native.rst
> +
```suggestion
```

2019-06-29 13:36 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +::
```suggestion
.. code-block:: XML
```

2019-06-29 13:36 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +
```suggestion
```

2019-06-29 13:36 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +The simulation control is the first part of the CYCLUS input file and is of the form:
```suggestion
The Cyclus input file begins with the ``<simulation>`` tag and ends with the ``</simulation>`` tag.
Within this space, the ``<control>`` block is the first section of the CYCLUS input file and is of the form:
```

2019-06-29 13:39 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +**duration**. **duration** is the number of months *CYCLUS* will
```suggestion
**duration**, the number of months *CYCLUS* will
```

2019-06-29 13:39 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +Using the simulation control template above and the table below, properly fill the template with the variables listed in the table below in your favorite text editor
```suggestion
Using the simulation control template above and the table below, properly fill the template 
with the variables listed in the table below in your favorite text editor.
```

2019-06-29 13:42 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +CYCLUS uses a time-step approach to march through time and determine what
```suggestion
|Cyclus| uses a time-step approach to march through time and determine what
```

2019-06-29 13:44 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +::
```suggestion
.. code-block:: XML
```

2019-06-29 13:44 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +::
```suggestion
.. code-block:: XML
```

2019-06-29 13:45 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +If you would like, you can space or tab the ``control`` header over for personal ease of reading the file but it is not necessary.
```suggestion
Adding spaces or tabs to indent the ``control`` header improves ease of reading. 
```

2019-06-29 13:45 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +3. After filling in the parameters listed in the table above tab out and close the control and simulation sections as:
```suggestion
3. After filling in the parameters listed in the table above, close the control and simulation sections as:
```

2019-06-29 13:46 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +::
```suggestion
.. code-block:: XML
```

2019-06-29 13:47 UTC, katyhuff commented on source/user/tutorial/sim_parm.rst
> +**Note**: There is two spaces between the end of the control section and end of the simulation section as the simulation section will hold the commodities, facilities, regions, institutions, and reci
```suggestion
**Note**: There are two blank lines between the end of the control section and end of the simulation section. This ection of the simulation block will hold the rest of the simulation parameter blocks (commodities, facilities, regions, institutions, and recipe blocks).
```

2019-07-03 23:02 UTC, FlanFlanagan commented on source/user/tutorial/run_cyclus_native.rst
> +In case your run did not succeed, you can retrieve =these files to continue:
```suggestion
In case your run did not succeed, you can retrieve these files to continue:
```

2020-09-11 04:56 UTC, gonuke requested changes
I got few a few files of this new tutorial and am a little concerned that it muddles some basic concepts, esp. archetypes vs prototypes.  Perhaps that's intentional, in which case we should discuss?

2020-09-11 04:56 UTC, gonuke commented on source/user/tutorial/sim_parm.rst
> +**Note**: There are two blank lines between the end of the control section and end of the simulation section. This ection of the simulation block will hold the rest of the simulation parameter blocks
```suggestion
**Note**: There are two blank lines between the end of the control section and end of the simulation section. This section of the simulation block will hold the rest of the simulation parameter blocks (commodities, facilities, regions, institutions, and recipe blocks).
```

2020-09-11 04:56 UTC, gonuke commented on source/user/tutorial/add_arche.rst
> +1. Go to the `archetypes
There is a way to discover archetypes at the command line.  Reading about them on the website does not confirm which ones are available on your system.

2020-09-11 04:56 UTC, gonuke commented on source/user/tutorial/add_arche.rst
> +-  Source: ``UraniumMine``, supplies natural uranium, a commodity we will call ``u-ore``
These describe prototypes and not archetypes.

2020-09-11 04:56 UTC, gonuke commented on source/user/tutorial/add_arche.rst
> +Now we will add the ``Region`` and ``Institution`` archetypes. These two
We haven't described the RIF hierarchy yet.  It probably makes more sense to leave this until later and have users edit this section.

2020-09-11 04:56 UTC, gonuke commented on source/user/tutorial/add_arche.rst
> +Concept: Source Archetype
This is a prototype and not an archetype.  We're getting ahead of ourselves.

2020-09-14 19:45 UTC, abachma2 commented
I understand what you are saying. The source, enrichment, etc. archetype concept sections of add_arche.rst are discussing the prototypes, not the archetypes. I think those sections should be moved to add_proto.rst, where the prototypes and facility sections in the code are discussed. Thoughts?

2021-01-05 22:53 UTC, nuclearkatie reviewed
Mostly cosmetic changes, a few questions. Overall, I think this looks good! Thanks to everyone who has contributed to this much-needed update to the tutorial

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/cyclus_tour.rst
> +The Github Repository that holds this tutorial is at https://github.com/arfc/cyclus-tutorial
I'm a bit lost trying to figure out how everything is linked together, but I hope this page is somehow connected to `source/user/tutorial/ipython_tour.rst`, which includes more info on why Jupyter Notebook/how to install and use. If not, maybe they should be?

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/data_explorer.rst
> +data that arises from a |cyclus| simulation. A variety of metrics, plots, and information can be
```suggestion
data that arises from a |Cyclus| simulation. A variety of metrics, plots, and information can be
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/data_explorer.rst
> +1. In your IPython notebook create the variables:
```suggestion
1. In your Jupyter notebook create the variables:
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/data_explorer.rst
> +In cyclus, facilities are defined by their ``prototype_id``. For example
```suggestion
In |Cyclus|, facilities are defined by their ``prototype_id``. For example
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/sim_parm.rst
>  * mine of natural uranium
```suggestion
* mine producing natural uranium
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/sim_parm.rst
> +5. <decay>:The |Cyclus| kernel has built-in experimental support for `Decay <http://fuelcycle.org/devdoc/decay.html>`_ calculations. Materials store the time since their last decay and agents are fre
```suggestion
5. <decay>:The |Cyclus| kernel has built-in experimental support for `Decay <http://fuelcycle.org/devdoc/decay.html>`_ calculations. Materials store the time since their last decay and agents are free to invoke the decay function on them as desired to decay them to the current simulation time. |Cyclus| can operate in 3 decay modes, with 1 additional mode likely to be added in a future release:
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/sim_parm.rst
> +- 'never' if all decay is turned off
```suggestion
- 'never', all decay is turned off
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/sim_parm.rst
> +- 'periodic' (future) automatically decays all materials in a simulation with some fixed frequency.
```suggestion
- 'periodic' (future), automatically decays all materials in a simulation with some fixed frequency. 
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/sim_parm.rst
> +including XML, JSON, and python. This tutorial
```suggestion
including XML, JSON, and Python. This tutorial
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/cyclus_tour.rst
> +An IPython notebook has four main areas:
```suggestion
A Jupyter notebook has four main areas:
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/add_arche.rst
> +`Third-Party <http://fuelcycle.org/user/index.html?highlight=third-party>`_ Archetypes complement the initial archetypes available in Cycamore and are not necessarily maintained by the Cyclus core de
```suggestion
`Third-Party <http://fuelcycle.org/user/index.html?highlight=third-party>`_ Archetypes complement the initial archetypes available in Cycamore and are not necessarily maintained by the |Cyclus| core development team.  Popular Third-Party Archetypes are:
```

2021-01-05 22:53 UTC, nuclearkatie commented on source/user/tutorial/add_arche.rst
> +A user identifies the simulation archetypes in the archetype block of the Cyclus input file.
```suggestion
A user identifies the simulation archetypes in the archetype block of the |Cyclus| input file. 
```

2021-01-11 20:44 UTC, katyhuff requested changes

2021-01-11 20:44 UTC, katyhuff commented on source/conf.py
> +    # 'papersize': 'letterpaper',
Not sure why these indentations are necessary (with these behind comment hashes (#), I'm not sure the indentation make a difference.)

2021-01-11 20:44 UTC, katyhuff commented
Finally did some review (sorry! such a long PR.) You did a great job @abachma2 !

2021-01-12 19:22 UTC, abachma2 commented on source/user/tutorial/add_second_reactor.rst
> +cycle time of 15 months, assembly size of 30160 kg, and power capacity 1000
That is a good question for @gtw2 and @jbae11.

2021-01-12 19:31 UTC, abachma2 commented on source/user/tutorial/cyclus_tour.rst
> +The Github Repository that holds this tutorial is at https://github.com/arfc/cyclus-tutorial
Based on ``index.rst``, neither of these pages are actually in the tutorial. But most of what is in ``ipython_tour.rst`` is in ``run_cyclus_native.rst``. I will go back through some of the files and make sure that needed info is required.

2021-01-12 19:44 UTC, abachma2 commented on source/cep/cep-0018-1.bib
> +keywords = {Supply chains;Networks;Equilibrium;Variational inequalities;Decentralized decision-making},
Not really. Probably force of habit when working with a bibtex file. I can remove it if it makes a difference.

2021-01-12 19:45 UTC, abachma2 commented on source/cep/cep-0018-1.bib
> +
No. I can remove it.

2021-02-03 19:29 UTC, nuclearkatie commented on source/user/tutorial/add_commod_recipe.rst
> +* 922350000 (ZZAAAMMMM)
Might also be confusing because at least the [nucname page on PyNE](http://pyne.io/theorymanual/nucname.html) uses S for state

2021-02-04 04:44 UTC, katyhuff commented
@abachma2 What's the status here?

2021-02-04 13:44 UTC, abachma2 commented on source/user/tutorial/add_commod_recipe.rst
> +* 922350000 (ZZAAAMMMM)
The pyne documentation uses S, but the recipe definition page on the cyclus website uses M. The cylcus pages should be consistent, but do they need to be consistent with pyne?

2021-02-04 13:52 UTC, abachma2 commented
I think I have addressed all of the comments from @katyhuff and @nuclearkatie (other than maybe the S vs M for energy state in the ZAID). I know @gonuke had some comments/changes earlier, not sure if he wanted to look at this before it gets merged. I don't know if other people (like @bam241) wanted to look over this before it gets merged.

I haven't made any changes to the data analysis part of the tutorial (``source/user/tutorial/data_explorer.rst``) because it has been removed from the tutorial right now and I included a reference to cymetric and the examples in that repository. I didn't want to remove the file altogether, because eventually I would like to re-write that page to use cymetric (it currently uses an ``analysis.py`` script) and include it back in the tutorial.

Overall, I think this is 95% done, with the last 5% for this PR to come from any further reviews. If no one else wants to add a review then the energy state in the ZAID needs to be resolved then this can be merged.

2021-02-04 19:25 UTC, katyhuff commented on source/user/tutorial/add_commod_recipe.rst
> +* 922350000 (ZZAAAMMMM)
```suggestion
* 922350000 (ZZAAAM)
```

2021-02-09 18:27 UTC, gonuke requested changes
I've done a first round of review.  I want to get these comments to you now since I'm not sure when I'll get to the rest....

2021-02-09 18:27 UTC, gonuke commented on source/user/tutorial/add_proto.rst
> +Concept: Reactor Prototype
Example?

2021-02-09 18:27 UTC, gonuke commented on source/user/tutorial/add_reg_inst.rst
> +and insitutions come from the ``agents`` library, rather than the ``cycamore``
There are also Regions and Institutions in the Cycamore library, but we don't use them here.  Maybe tweak the language to make this more clear.

2021-02-09 18:27 UTC, gonuke commented on source/user/tutorial/add_reg_inst.rst
> +Since these are all archetypes, no matter what library they're from, we must append the `agent` archetype block
This isn't clear to me.  Do you mean that we have to append these particular `spec` blocks into the existing `archetypes` block?

2021-02-09 18:27 UTC, gonuke commented on source/user/tutorial/run_cyclus_native.rst
> +Activity: Retrieve your Results for Analysis
Is "Retrieve" the right word here?

2021-02-09 18:27 UTC, gonuke commented on source/user/tutorial/add_second_reactor.rst
> +cycle time of 15 months, assembly size of 30160 kg, and power capacity 1000
I agree that it would be better to make this some multiple of 6 months

2021-02-09 18:27 UTC, gonuke commented on source/user/tutorial/add_deploy.rst
> +Concept: DeployInst
"Example" not "Concept"

2021-02-09 19:36 UTC, nuclearkatie commented on source/user/tutorial/sim_parm.rst
> +2. <duration>: the number of months to be simulated
OO I just wondered about that today as I was giving a live demo to some LANL folks.... it also says "duration (required once) - the time duration of the simulation (in months)" in the [user guide page on control](http://fuelcycle.org/user/input_specs/control.html)

2021-02-11 17:06 UTC, abachma2 commented on source/user/tutorial/sim_parm.rst
> +6. Description: A brief description of your simulation.
I'm not sure. I think this is a relic from the description field of cyclist. I don't think I have seen an xml input with this field. Does it still exist? Does anyone use it? Should I just delete this?

2021-02-11 17:25 UTC, abachma2 commented on source/user/tutorial/add_commod_recipe.rst
> +Suppliers then respond to the series of requests with a **bid**. A bid
Any thoughts on a better spot?

2021-02-22 19:18 UTC, gonuke commented on source/user/tutorial/sim_parm.rst
> +6. Description: A brief description of your simulation.
I think we should just delete this

2021-02-23 16:25 UTC, abachma2 commented
Just pushed what may be the final changes, specifically most of the comments from @gonuke, and adjustment of ZAID. There may still be some inconsistencies with `example` vs `activity`. I can go back through and work on that, or we can save that for another PR.

2021-02-24 15:00 UTC, katyhuff approved these changes

2021-02-24 15:00 UTC, katyhuff commented on source/user/tutorial/mod_rxtr.rst
> +--------------------
does this render right? Underline may not be long enough.

2021-02-24 15:20 UTC, abachma2 commented on source/user/tutorial/mod_rxtr.rst
> +--------------------
When I build the pages locally, this section title renders the same as the others.

2021-02-24 15:21 UTC, abachma2 commented
I made Issue #307 to keep track of possible future changes to make, but this PR is complete and ready to merge pending approval from @gonuke.

2021-02-24 16:51 UTC, nuclearkatie approved these changes
Great work @abachma2 and everyone else who contributed, this has been a long time coming! Very excited to see it live and be able to send new users to follow it

2021-02-25 03:17 UTC, gonuke commented on source/user/tutorial/mod_rxtr.rst
> +--------------------
It may give a warning and render fine...

2021-02-25 03:19 UTC, gonuke approved these changes
Thanks for sticking with this @abachma2 - Mars isn't the only one with perseverance!

2021-02-25 19:01 UTC, merged

2021-02-25 19:01 UTC, katyhuff commented
Merged! Thanks everyone!