Update Python API for archetype development
cyclus/cyclus.github.com pull request #326
Opened 2024-01-24 15:57 UTC by abachma2

This PR reflects changes made in [Cyclus PR #1594](https://github.com/cyclus/cyclus/pull/1594) to add some functionality to the Python API for creating material requests. There are also some small typo fixes on a few other pages around the site. 

This should *not* be merged until after Cyclus PR #1594 is merged.

2024-02-07 02:44 UTC, gonuke requested changes
A few little things... does this mean that you are actually able to build the website still?

2024-02-07 02:44 UTC, gonuke commented on source/arche/dre.rst
> +        commods = {"FuelA": target_a}, {"FuelB": target_b}
should this be a list?
```suggestion
        commods = [{"FuelA": target_a}, {"FuelB": target_b}]
```

2024-02-07 02:44 UTC, gonuke commented on source/arche/dre.rst
> +        port = {"commodities":commods, "constraints":request_qty
```suggestion
        port = {"commodities":commods, "constraints":request_qty}
```

2024-02-07 02:44 UTC, gonuke commented on source/arche/dre.rst
> +        port = {"commodities":commods, "constraints":request_qty
```suggestion
        port = {"commodities":commods, "constraints":request_qty}
```

2024-02-07 02:44 UTC, gonuke commented on source/arche/tutorial_py/toolkit.rst
> +in the schema and therefore will not appear in the Cyclus UI either.
I'm not sure how to correct this.  It was referring to a now-deprecated UI called "Cycic".  While we may not want to leave references to that lying around, I'm not sure that this is correct, either.

2024-02-08 18:07 UTC, abachma2 commented
I can at least build the preview locally with `make gh-preview`. I don't know about a full build that would be live on the webpages.

2024-02-08 18:11 UTC, abachma2 commented on source/arche/dre.rst
> +        commods = {"FuelA": target_a}, {"FuelB": target_b}
No. If you don't include "commodities" as one of the keys, then it expects the value to be a Material or Resource. I intentionally left this structure as the most basic thing you can return from this function in the python API.

2024-02-08 18:17 UTC, abachma2 commented on source/arche/tutorial_py/toolkit.rst
> +in the schema and therefore will not appear in the Cyclus UI either.
We can just take out that clause then. I don't think I've seen any other references to this.

2024-02-08 19:55 UTC, gonuke commented on source/arche/dre.rst
> +        commods = {"FuelA": target_a}, {"FuelB": target_b}
Then I'm not sure what the comma means here?  They aren't grouped into a data structure in any way

2024-02-08 19:58 UTC, abachma2 commented on source/arche/dre.rst
> +        commods = {"FuelA": target_a}, {"FuelB": target_b}
You are correct. It should be all one dictionary. Thanks for catching that. I've corrected it.

2024-02-08 20:30 UTC, gonuke approved these changes

2024-02-08 20:31 UTC, gonuke commented
Thanks @abachma2

2024-02-08 20:31 UTC, merged

2024-02-08 20:31 UTC, gonuke commented
Now we have to figure out how to publish an update successfully... :)

2024-02-08 20:32 UTC, abachma2 commented
I'll work on that next week and ping y'all in the slack if I run into big issues.