Update list of contributors
cyclus/cyclus.github.com pull request #342
Opened 2024-03-21 17:35 UTC by nsryan2

This PR changes the explicit list of contributors to links to Cyclus, Cymetric, and Cycamore GitHub contributors.

2024-03-21 17:40 UTC, abachma2 requested changes
Thanks for making this change. One small working change I would suggest.

2024-03-21 17:43 UTC, nuclearkatie approved these changes
Thanks for this, @nsryan2! Always nice to replace something that needs to be updated regularly with an automated system/link

2024-03-21 18:56 UTC, gonuke commented
I am sure there was a reason we didn't do this before, but can't recall... it might be because these contributor graphs highlight metrics (commits/additions/deletions) that we didn't think were valuable....  But not a reason to disagree with this change.

2024-03-21 18:57 UTC, gonuke commented
It's too bad there is not a view that is just a list of contributors... (bonus points for the person who can produce that from git 😀 )

2024-03-21 22:07 UTC, nuclearkatie commented
You could use the output of git shortlog, but that would require updates or additional automation 
`git shortlog --summary`

Also, trying it on my machine also results in a number of different people who show up in different ways, perhaps because they used different machines where they set their `git config user.name` in a slightly different way. For example, @abachma2 is on the  list as `abachma2`, `abachmann`, and `Amanda`, and you @gonuke are there as both `Paul P.H. Wilson` and `Paul Wilson`. I'm not sure how/if you can get github usernames.

2024-03-21 22:52 UTC, gonuke commented
> Also, trying it on my machine also results in a number of different people who show up in different ways

yeah... that's a problem

2024-03-29 13:51 UTC, gonuke commented
@abachma2 - I committed your recommended change - please confirm that you're ok with this and merge.

2024-03-29 13:54 UTC, abachma2 approved these changes
Thanks for making this change @gonuke! LGTM.

2024-03-29 13:59 UTC, merged