Update small items on the website
cyclus/cyclus.github.com pull request #362
Opened 2024-04-11 21:06 UTC by abachma2

This PR addresses some of the items in #337, such as missing `>` in the tutorial, fixing links to places, updating projects that use Cyclus, listing funding sources for Cyclus, etc. Others came up with some of the items this PR addresses, so definitely welcoming feedback on some of the changes.

2024-04-14 19:11 UTC, gonuke reviewed
A couple of little suggestions - thanks @abachma2

2024-04-14 19:11 UTC, gonuke commented on source/index.rst
> +
Should we generate some news? Maybe @abachma2's PhD?

2024-04-14 19:11 UTC, gonuke commented on source/user/install.rst
> +load the sqlite file into Cyclist for data visualization, or use your favorite sqlite browser to peruse.
Shouldn't we remove reference to `Cyclist` here?

2024-04-14 19:12 UTC, gonuke requested changes
I think this needs an update/rebase, too

2024-04-14 22:28 UTC, bennibbelink requested changes
Suggested a couple minor changes.  I have one additional question about the example `setup.py` in this tutorial - why is `'xo'` included as a script?  Is it just included as an indication that users can include their own scripts in the package or is actually necessary for this tutorial?  I removed this dependency from the Dockerfile in [#1735](https://github.com/cyclus/cyclus/pull/1735) and want to make sure I'm not breaking anything.

2024-04-14 22:28 UTC, bennibbelink commented on source/arche/tutorial_py/setup.rst
> +    ~/tutorial $ pip install .
```suggestion
    ~/tutorial $ python -m pip install .
```

2024-04-14 22:28 UTC, bennibbelink commented on source/arche/tutorial_py/setup.rst
>  Let's now make an example input file in a special ``input`` directory:
GitHub isn't letting me add a comment on line 84 but I think it's missing a `py` after `input/storage.`

2024-04-15 13:48 UTC, abachma2 commented on source/index.rst
> +
@nuclearkatie had an item about the latest news being from 2018, but I wasn't sure what news items we could add. We could add an announcement about the current NEUP grant, show that there is active development on the code.

2024-04-15 13:58 UTC, abachma2 commented
> I think this needs an update/rebase, too

Do we do rebase, or merge with this repo? I think rebase.

2024-04-15 14:05 UTC, abachma2 commented
> Suggested a couple minor changes. I have one additional question about the example `setup.py` in this tutorial - why is `'xo'` included as a script? Is it just included as an indication that users can include their own scripts in the package or is actually necessary for this tutorial? I removed this dependency from the Dockerfile in [#1735](https://github.com/cyclus/cyclus/pull/1735) and want to make sure I'm not breaking anything.

I don't know about that one. @gonuke might have some more insight on what that does for the build.

2024-04-15 14:52 UTC, bennibbelink requested changes

2024-04-15 14:52 UTC, bennibbelink commented on source/index.rst
> +    user/install
I'm not seeing the `toctree` under Quick Start.  This screenshot is from the build artifact generated by CI:

<img width="1361" alt="Screenshot 2024-04-15 at 9 45 54 AM" src="https://github.com/cyclus/cyclus.github.com/assets/79653949/9116efbb-0e9e-4cb2-a601-2d6561f4271b">

2024-04-15 14:52 UTC, bennibbelink commented on source/user/install.rst
> +1. Run Cyclus with a Sample XML File
```suggestion
2. Run Cyclus with a Sample XML File
```

2024-04-15 14:52 UTC, bennibbelink commented on source/index.rst
> +**June 1st, 2018:** :doc:` <newsletters/may2018>`
Add text for this `:doc:` reference.  Currently rendering incorrectly: 
```suggestion
**June 1st, 2018:** :doc:`Cyclus Newsletter Spring 2018! <newsletters/may2018>`
```
<img width="725" alt="Screenshot 2024-04-15 at 9 49 21 AM" src="https://github.com/cyclus/cyclus.github.com/assets/79653949/b9a93a69-1c38-4cf4-862e-0692e4ece011">

2024-04-15 15:05 UTC, abachma2 commented
Good catches @bennibbelink. Hopefully it all renders correctly now.

2024-04-15 16:04 UTC, bennibbelink approved these changes
Thanks @abachma2!

2024-04-15 22:16 UTC, gonuke commented
> > Suggested a couple minor changes. I have one additional question about the example `setup.py` in this tutorial - why is `'xo'` included as a script? Is it just included as an indication that users can include their own scripts in the package or is actually necessary for this tutorial? I removed this dependency from the Dockerfile in [#1735](https://github.com/cyclus/cyclus/pull/1735) and want to make sure I'm not breaking anything.
> 
> I don't know about that one. @gonuke might have some more insight on what that does for the build.

`xo` is a lightweight python-based editor written by Scopatz - I think we can probably get rid of it and it's dependency.

2024-04-18 13:54 UTC, bennibbelink requested changes
In that case @abachma2 are you opposed to removing `'xo'` from line 63 of `tutorial_py/setup.rst`?

2024-04-18 14:00 UTC, abachma2 commented
I am always down for removing unneeded dependencies from installation instructions.

2024-04-18 14:31 UTC, bennibbelink approved these changes
Looks good.  Are we waiting to include some news items in this PR or should we merge and save that for another PR?

2024-04-18 14:34 UTC, abachma2 commented
I don't think that's a blocking thing for this PR. I think we have enough other items in #337 that can include a new News item in a later PR. Maybe we can discuss somewhere else what a good news item would be.

2024-04-18 16:35 UTC, bennibbelink commented
I took the liberty of rebasing this PR.  @gonuke does that resolve your requested changes?

2024-04-20 17:01 UTC, gonuke approved these changes

2024-04-20 17:02 UTC, merged