More general updates
cyclus/cyclus.github.com pull request #367
Opened 2024-04-29 21:56 UTC by abachma2

This PR addresses some of the issues raised in #337, specifically:
- some of the build warnings from `source/cep/cep27.rst`
- adding a news item 
- adding a missing version release for v1.5.5.
- fixing typos/small issues identified by @dean-krueger 
- removing the `data_explorer.rst` from the user tutorial
- removing mention of cloud for running cyclus from user tutorial.

2024-05-04 18:08 UTC, bennibbelink commented on source/previous/v1.5.5.rst
> +
In our meeting on Monday we discussed modifying the "Cyclus Previous Versions" page to simply reference the GitHub releases.  The releases already have the changes in the descriptions so it probably isn't necessary to copy/paste that information into the site as well.  Do you have any thoughts about this?

2024-05-06 21:10 UTC, abachma2 commented on source/previous/v1.5.5.rst
> +
So something like pointing to [this page](https://github.com/cyclus/cyclus/releases/tag/1.5.5) for the 1.5.5 release? Instead of having separate web pages for the releases?

2024-05-06 22:04 UTC, bennibbelink commented on source/previous/v1.5.5.rst
> +
Not sure if we even need to link each release... we could say that all the releases can be found at [this page](https://github.com/cyclus/cyclus/releases) so we don't need to manually copy/paste info from Github to the site with each release.  I might have misunderstood the group consensus though - @gonuke what did you have in mind?

2024-05-06 22:06 UTC, bennibbelink commented
Not sure if you saw my [PR](https://github.com/abachma2/cyclus.github.com/pull/1) to your branch.  This small change could be thrown into this PR.

2024-05-06 22:24 UTC, bennibbelink requested changes

2024-05-06 22:24 UTC, bennibbelink commented on source/previous/index.rst
> +packages are also available below.
Do we need to maintain this table of zips/tarballs still?

2024-05-06 22:24 UTC, bennibbelink commented on source/news/fy24neup.rst
> +.. _MARKAL: http://www.iea-etsap.org/web/Markal.asp
```suggestion

```

2024-05-06 22:24 UTC, bennibbelink commented on source/news/fy24neup.rst
> +.. _GCAM: http://www.globalchange.umd.edu/models/gcam/
```suggestion
```

2024-05-06 22:24 UTC, bennibbelink commented on source/user/tutorial/index.rst
> -    launch_cyclus
I see this removes "Using Cyclus in the Cloud".  There is another reference to the cloud service in `user/tutorial/install_launch_cyclus` that should probably also be removed.

2024-05-07 01:17 UTC, gonuke commented on source/previous/index.rst
> +packages are also available below.
While I agree that it would be great to avoid maintaining the table, it's nice to get a compact view of releases/release dates.... wonder if can automate that in a future update (i.e. make an issue)

2024-05-07 01:23 UTC, gonuke requested changes
Not sure why we're deleting the data explorer page?

2024-05-07 01:23 UTC, gonuke commented on source/user/tutorial/data_explorer.rst
Why are we getting rid of this?

2024-05-07 13:11 UTC, abachma2 commented on source/user/tutorial/data_explorer.rst
1. It's not actually called anywhere, like no other page links to it
2. It uses a python package (`analaysis.py`) that I don't know where people are supposed to get access to it. 
3. We link to the Cymetric GitHub in one of the pages for how to use that tool for analysis
4. We are missing a bunch of figures that are supposed to go on this page, and I think it would be nontrivial to recreate them, especially since I don't have the `analysis.py` to replicate the procedure.

2024-05-07 13:12 UTC, abachma2 commented on source/previous/index.rst
> +packages are also available below.
All of the zips are on the github tags page. Maybe link to those?

2024-05-07 13:13 UTC, abachma2 commented on source/user/tutorial/index.rst
> -    launch_cyclus
I'll make sure that gets removed. This cloud service isn't working, so we shouldn't get users' hopes up that they don't have to install locally.

2024-05-07 13:41 UTC, abachma2 commented
One note about removing the release notes from the website: Some of the Release notes with the tags on GitHub point to those pages ([like v1.3](https://github.com/cyclus/cyclus/releases/tag/1.3.0)). Should we just copy the contents of the web pages to these notes? To make sure we don't lose anything and it's all in the same place?

2024-05-07 13:47 UTC, gonuke commented on source/user/tutorial/data_explorer.rst
Thanks, I it didn't appear to be so immediately out of date on my scan during review, but that all makes sense.

2024-05-07 13:51 UTC, abachma2 commented on source/user/tutorial/data_explorer.rst
Fair question. And I think I included some of this information in the commit message when I deleted it, so hopefully it helps to answer future questions.

2024-05-08 15:57 UTC, gonuke commented
> One note about removing the release notes from the website: Some of the Release notes with the tags on GitHub point to those pages ([like v1.3](https://github.com/cyclus/cyclus/releases/tag/1.3.0)). Should we just copy the contents of the web pages to these notes? To make sure we don't lose anything and it's all in the same place?

It looks like v1.3 may have been the only one and I just copy/pasted the content to the release info on each of Cyclus/Cycamore/Cymetric

2024-05-08 15:58 UTC, gonuke approved these changes

2024-05-08 16:19 UTC, bennibbelink approved these changes

2024-05-08 16:20 UTC, merged