Deprecate `ResourceBuff`
cyclus/cyclus.github.com pull request #370
Opened 2024-05-18 18:10 UTC by bennibbelink

- Updates the toolkit documentation to reflect the deprecation of `ResourceBuff`
- Updates Dockerfile to use `python3` instead of version agnostic `python`

2024-05-19 15:17 UTC, gonuke requested changes
Just wondering about the placement of the deprecation note.

2024-05-19 15:17 UTC, gonuke commented on source/arche/toolkit.rst
> +    ResourceBuff has been deprecated in favor of ``ResBuf``.
I wonder where it is best to include this note?  Maybe at the end of the `ResBuf` preamble?

2024-05-20 12:59 UTC, bennibbelink commented on source/arche/toolkit.rst
> +    ResourceBuff has been deprecated in favor of ``ResBuf``.
Here?

![image](https://github.com/cyclus/cyclus.github.com/assets/79653949/14e1962f-e7ee-4da9-8b87-766a751e976b)

2024-05-20 18:18 UTC, gonuke approved these changes

2024-05-20 18:18 UTC, merged