Add python script to generate previous releases table
cyclus/cyclus.github.com pull request #382
Opened 2024-08-09 01:12 UTC by bennibbelink

This will require a rebase after #381 is merged (for the `mamba update --all` line).  Runs a python script to construct the previous releases table so we don't have to manually update it on release.  Closes #369

2024-09-20 00:54 UTC, bennibbelink commented
The table is in `/previous/index.html` for reference

2024-09-22 20:37 UTC, gonuke requested changes
Thanks - I added a suggestion for a  link to the Github release page as well...

2024-09-22 20:37 UTC, gonuke commented on source/releases.py
> +   * - {version}
How about we add a link to the Github Release page?
```suggestion
        tar_url = release['tarball_url']
        web_url = release['html_url']
        table_text += f'''
   * - `{version} <{web_url}>`
```

2024-09-22 23:40 UTC, bennibbelink commented on source/releases.py
> +   * - {version}
Good idea, LGTM

2024-09-23 00:05 UTC, gonuke approved these changes
Thanks @bennibbelink

2024-09-23 00:05 UTC, merged